name = "jinmin-portfolio"
compatibility_date = "2026-08-16"

[env.production]

[[d1_databases]]
binding = "DB"
database_name = "portfolio-analytics"
database_id = "bf01ad10-11a3-44d8-8653-a767a13f97bc"
